### ISSUE TITLE
2022.09.27 미팅에 나온 수정 사항

### ISSUE THREAD

**Issue by saseungmin** [jenny-harang/soople#502]
- [x] 팀원 모달에서 링크가 긴 경우 대응 #503
- [x] 팀원 모달에서 스크롤 그라데이션 추가 #503 
- [ ] 팀 모집하기 > 등록하기 모달에서 600px로 고정되어 있는데 모바일 반응형 적용이 450px 이하일때 적용되어서 모달이 깨지는 현상
- [ ] TextArea를 입력하는 시점에는 Enter 적용 가능하도록 변경 #504 
  - 댓글, 신청 시 소개글, 팀원들에게 보내는 메시지는 Enter 적용해서 보여주고 짧은 소개글만 띄어쓰기 적용해서 보여주기
- [ ] 풀모달 말고 Dialog 모달은 외부 영역 클릭 시 종료 #505
- [ ] PC에서 모달 에니메이션 변경 / 모바일에서 모달 bottom up 에니메이션 bounce 삭제 #505
